version: 0.2

env:
  variables:
    APP_DIR: /home/ec2-user/calculadora

phases:
  install:
    commands:
      - echo "Installing SSH tools..."
      - yum install -y openssh-clients

  build:
    commands:
      - echo "Setting SSH key..."
      - chmod 600 key.pem

  post_build:
    commands:
      - echo "Preparing remote directory..."
      - ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@$EC2_IP "rm -rf $APP_DIR && mkdir -p $APP_DIR"

      - echo "Uploading project to EC2..."
      - scp -o StrictHostKeyChecking=no -i key.pem -r ./* ec2-user@$EC2_IP:$APP_DIR/

      - echo "Building and running container on EC2..."

      - |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@$EC2_IP << 'EOF'
          set -e

          cd /home/ec2-user/calculadora

          echo "Current directory:"
          pwd
          ls -la

          docker stop calculadora || true
          docker rm calculadora || true

          echo "Building Docker image..."
          docker build -t calculadora-app .

          echo "Running container..."
          docker run -d -p 80:3000 --name calculadora calculadora-app:latest
        EOF

artifacts:
  files:
    - '**/*'